version: "3"

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: front-desafio
    ports:
      - 8080:8080
    tty: true
    restart: always
    networks:
      - api-sgf
    volumes:
      - .:/user/app-front/app

networks:
  api-sgf: